/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface OracleHelperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cachedPrice"
      | "cachedPriceTimestamp"
      | "updateCachedPrice"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TokenPriceUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "cachedPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cachedPriceTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCachedPrice",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "cachedPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cachedPriceTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCachedPrice",
    data: BytesLike
  ): Result;
}

export namespace TokenPriceUpdatedEvent {
  export type InputTuple = [
    currentPrice: BigNumberish,
    previousPrice: BigNumberish,
    cachedPriceTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    currentPrice: bigint,
    previousPrice: bigint,
    cachedPriceTimestamp: bigint
  ];
  export interface OutputObject {
    currentPrice: bigint;
    previousPrice: bigint;
    cachedPriceTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleHelper extends BaseContract {
  connect(runner?: ContractRunner | null): OracleHelper;
  waitForDeployment(): Promise<this>;

  interface: OracleHelperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cachedPrice: TypedContractMethod<[], [bigint], "view">;

  cachedPriceTimestamp: TypedContractMethod<[], [bigint], "view">;

  updateCachedPrice: TypedContractMethod<
    [force: boolean],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cachedPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cachedPriceTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateCachedPrice"
  ): TypedContractMethod<[force: boolean], [bigint], "nonpayable">;

  getEvent(
    key: "TokenPriceUpdated"
  ): TypedContractEvent<
    TokenPriceUpdatedEvent.InputTuple,
    TokenPriceUpdatedEvent.OutputTuple,
    TokenPriceUpdatedEvent.OutputObject
  >;

  filters: {
    "TokenPriceUpdated(uint256,uint256,uint256)": TypedContractEvent<
      TokenPriceUpdatedEvent.InputTuple,
      TokenPriceUpdatedEvent.OutputTuple,
      TokenPriceUpdatedEvent.OutputObject
    >;
    TokenPriceUpdated: TypedContractEvent<
      TokenPriceUpdatedEvent.InputTuple,
      TokenPriceUpdatedEvent.OutputTuple,
      TokenPriceUpdatedEvent.OutputObject
    >;
  };
}
