/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SenderCreator,
  SenderCreatorInterface,
} from "../../../contracts/core/SenderCreator";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initCode",
        type: "bytes",
      },
    ],
    name: "createSender",
    outputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "entryPoint",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a080604052346100285733608052610225908161002e8239608051818181604f015260d70152f35b600080fdfe6080806040526004908136101561001557600080fd5b600091823560e01c918263570e1a361461008157505063b0d691fe1461003a57600080fd5b3461007e578060031936011261007e576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b80fd5b8390346101eb57602092836003193601126101e75780359067ffffffffffffffff908183116101e357366023840112156101e357828101358281116101a05736602482860101116101a0576001600160a01b03947f0000000000000000000000000000000000000000000000000000000000000000861633036101a45750806014116101a05760131981019280841161018d5760405192600b8301601f19908116603f011684019182118483101761017a5750602488959388600c819795829560405286845289840196603889018837830101525193013560601c5af19180519215610172575b5060405191168152f35b915083610168565b634e487b7160e01b885260419052602487fd5b634e487b7160e01b875260418352602487fd5b8580fd5b60649088808562461bcd60e51b845283015260248201527f414139372073686f756c642063616c6c2066726f6d20456e747279506f696e746044820152fd5b8480fd5b8280fd5b5080fdfea26469706673582212207456905ed1481cee0043edb23bce005c4b3f16491a700a7149e22c20c95b65d164736f6c63430008130033";

type SenderCreatorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SenderCreatorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SenderCreator__factory extends ContractFactory {
  constructor(...args: SenderCreatorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SenderCreator & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SenderCreator__factory {
    return super.connect(runner) as SenderCreator__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SenderCreatorInterface {
    return new Interface(_abi) as SenderCreatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SenderCreator {
    return new Contract(address, _abi, runner) as unknown as SenderCreator;
  }
}
