/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISenderCreator,
  ISenderCreatorInterface,
} from "../../../contracts/interfaces/ISenderCreator";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initCode",
        type: "bytes",
      },
    ],
    name: "createSender",
    outputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISenderCreator__factory {
  static readonly abi = _abi;
  static createInterface(): ISenderCreatorInterface {
    return new Interface(_abi) as ISenderCreatorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISenderCreator {
    return new Contract(address, _abi, runner) as unknown as ISenderCreator;
  }
}
